# Generated by Django 6.0.5 on 2026-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_doctors_numero_ordre_medecins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
    ]
