# Generated by Django 6.0.5 on 2026-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doctors_actif_doctors_horaires_travail_doctors_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='horaires_travail',
            new_name='horaire_travail',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='blood_group',
            new_name='groupe_sanguin',
        ),
        migrations.AddField(
            model_name='doctors',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='date_creation_dossier',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patients',
            name='telephone_parent',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
