# Generated by Django 6.0.5 on 2026-05-23 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_horaires_travail_doctors_horaire_travail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='numero_ordre_medecins',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='traceaction',
            name='id_enregistrement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DOCTOR', 'Médecin'), ('PARENT', 'Parent'), ('SECRETAIRE', 'Secrétaire')], max_length=15),
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau', models.CharField(blank=True, max_length=100)),
                ('telephone_interne', models.CharField(blank=True, max_length=30)),
                ('horaires_service', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretaire_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secrétaire',
                'verbose_name_plural': 'Secrétaires',
            },
        ),
    ]
