-- ============================================================
-- HOPITAL PEDIATRIQUE ORAN — BASE DE DONNEES FINALE
-- Version nettoyée et corrigée de hospital_db_talya_v4.sql
-- Toutes les tables correspondent exactement aux modèles Django
-- PostgreSQL — exécuter APRÈS python manage.py migrate
-- ============================================================

-- ============================================================
-- STEP 1: SPECIALTIES (inchangé)
-- ============================================================
INSERT INTO users_specialty (name) VALUES ('Pneumologie pédiatrique');
INSERT INTO users_specialty (name) VALUES ('Pédiatrie générale');
INSERT INTO users_specialty (name) VALUES ('Ophtalmologie pédiatrique');

-- ============================================================
-- STEP 2: ADDRESSES (inchangé — 36 adresses)
-- ============================================================
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('12 Rue Larbi Ben Mhidi',          'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('5 Cité des 1000 Logements',        'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('7 Rue de la Paix',                 'Oran',           'Es Senia',        '31130');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('3 Boulevard Millénium',            'Oran',           'Bir El Djir',     '31200');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('22 Rue Hassiba Ben Bouali',        'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('9 Cité USTO',                      'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('14 Rue Ahmed Zabana',              'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('88 Cité Petit Lac',                'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('2 Rue des Frères Bouadou',         'Oran',           'Bir El Djir',     '31200');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('45 Boulevard Soummam',             'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('17 Cité Bousfer',                  'Oran',           'Bousfer',         '31150');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('33 Rue Mohamed Khemisti',          'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('6 Impasse Belcourt',               'Oran',           'Es Senia',        '31130');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('19 Rue de Mostaganem',             'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('52 Cité El Yasmine',               'Oran',           'Bir El Djir',     '31200');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('8 Rue Abdelkader Azzout',          'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('24 Cité Gambetta',                 'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('11 Rue du 1er Novembre',           'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('36 Cité ZHUN Est',                 'Oran',           'Bir El Djir',     '31200');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('3 Rue Houari Boumediene',          'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('77 Boulevard Colonel Lotfi',       'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('15 Cité 5 Juillet',                'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('29 Rue Cheikh Larbi Tébessi',      'Oran',           'Es Senia',        '31130');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('4 Allée des Orangers',             'Oran',           'Bousfer',         '31150');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('18 Cité Petit Lac Ouest',          'Oran',           'Oran',            '31000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('7 Rue des Martyrs',                'Mostaganem',     'Mostaganem',      '27000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('21 Cité El Wiam',                  'Mostaganem',     'Mostaganem',      '27000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('5 Rue Emir Abdelkader',            'Ain Témouchent', 'Ain Témouchent',  '46000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('13 Cité OPGI',                     'Ain Témouchent', 'Ain Témouchent',  '46000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('9 Boulevard de la République',     'Mascara',        'Mascara',         '29000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('32 Rue Khaled Ibn El Walid',       'Mascara',        'Mascara',         '29000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('16 Cité 200 Logements',            'Sidi Bel Abbes', 'Sidi Bel Abbes',  '22000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('44 Avenue Larbi Ben Mhidi',        'Sidi Bel Abbes', 'Sidi Bel Abbes',  '22000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('6 Rue 8 Mai 1945',                 'Relizane',       'Relizane',        '48000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('27 Cité Sonatrach',                'Tlemcen',        'Tlemcen',         '13000');
INSERT INTO users_address (address_line, region, city, code_postal) VALUES ('38 Rue Abou Mediène',              'Tlemcen',        'Tlemcen',         '13000');

-- ============================================================
-- STEP 3: USERS
-- FIX: MEDECIN → DOCTOR (Django role choice)
-- REMOVED: users_role, users_admin, users_parent inserts 
-- ============================================================

-- ADMIN
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,TRUE,'admin','Admin','Systeme','admin@hopital-oran.dz',TRUE,TRUE,NOW(),'ADMIN','0555000000',1);

-- SECRETAIRES
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'sec.fatima','Fatima','Benouali','fatima.benouali@hopital-oran.dz',FALSE,TRUE,NOW(),'ADMIN','0550100200',11);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'sec.karima','Karima','Bensaid','karima.bensaid@hopital-oran.dz',FALSE,TRUE,NOW(),'ADMIN','0550200300',12);

-- DOCTORS (FIX: MEDECIN → DOCTOR)
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'dr.amrani','Karim','Amrani','amrani@hopital-oran.dz',FALSE,TRUE,NOW(),'DOCTOR','0555111111',2);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'dr.khelif','Samira','Khelif','khelif@hopital-oran.dz',FALSE,TRUE,NOW(),'DOCTOR','0555222222',3);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'dr.benali','Yacine','Benali','benali@hopital-oran.dz',FALSE,TRUE,NOW(),'DOCTOR','0555333333',4);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'dr.meziani','Fatima','Meziani','meziani@hopital-oran.dz',FALSE,TRUE,NOW(),'DOCTOR','0555444444',5);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id)
VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'dr.boudiaf','Omar','Boudiaf','boudiaf@hopital-oran.dz',FALSE,TRUE,NOW(),'DOCTOR','0555555555',6);

-- PARENTS (31 parents)
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.lina','Lina','Boudiaf','lina.boudiaf@gmail.com',FALSE,TRUE,NOW(),'PARENT','0661111111',13);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.ahmed','Ahmed','Mansouri','ahmed.mansouri@gmail.com',FALSE,TRUE,NOW(),'PARENT','0662222222',14);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.yousra','Yousra','Ouali','yousra.ouali@gmail.com',FALSE,TRUE,NOW(),'PARENT','0663333333',15);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.karim','Karim','Djaafri','karim.djaafri@gmail.com',FALSE,TRUE,NOW(),'PARENT','0664444444',16);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.nadia','Nadia','Belarbi','nadia.belarbi@gmail.com',FALSE,TRUE,NOW(),'PARENT','0665555555',17);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.sofiane','Sofiane','Rahmani','sofiane.rahmani@gmail.com',FALSE,TRUE,NOW(),'PARENT','0666666666',18);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.meriem','Meriem','Bensalem','meriem.bensalem@gmail.com',FALSE,TRUE,NOW(),'PARENT','0667777777',19);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.hassan','Hassan','Tlemcani','hassan.tlemcani@gmail.com',FALSE,TRUE,NOW(),'PARENT','0668888888',20);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.houria','Houria','Saidi','houria.saidi@gmail.com',FALSE,TRUE,NOW(),'PARENT','0669999999',21);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.farid','Farid','Bengana','farid.bengana@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770111222',22);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.zineb','Zineb','Ferroukhi','zineb.ferroukhi@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770222333',23);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.mourad','Mourad','Kaci','mourad.kaci@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770333444',24);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.amina','Amina','Cherif','amina.cherif@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770444555',25);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.rachid','Rachid','Boussaid','rachid.boussaid@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770555666',26);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.hayat','Hayat','Hadj','hayat.hadj@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770666777',27);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.bilal','Bilal','Bouziane','bilal.bouziane@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770777888',28);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.sabrina','Sabrina','Mekki','sabrina.mekki@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770888999',29);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.omar','Omar','Ziani','omar.ziani@gmail.com',FALSE,TRUE,NOW(),'PARENT','0770999000',30);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.naima','Naima','Ghali','naima.ghali@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771100200',21);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.tarek','Tarek','Medjdoub','tarek.medjdoub@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771200300',22);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.sihem','Sihem','Benyahia','sihem.benyahia@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771300400',26);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.lotfi','Lotfi','Haddar','lotfi.haddar@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771400500',27);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.malika','Malika','Bensmain','malika.bensmain@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771500600',28);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.yacine','Yacine','Dif','yacine.dif@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771600700',29);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.wafa','Wafa','Baali','wafa.baali@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771700800',30);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.abdelkader','Abdelkader','Tebbal','abdelkader.tebbal@gmail.com',FALSE,TRUE,NOW(),'PARENT','0771800900',31);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.hanane','Hanane','Sellal','hanane.sellal@gmail.com',FALSE,TRUE,NOW(),'PARENT','0772000100',32);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.hocine','Hocine','Boudinar','hocine.boudinar@gmail.com',FALSE,TRUE,NOW(),'PARENT','0772100200',33);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.khadija','Khadija','Bouhelal','khadija.bouhelal@gmail.com',FALSE,TRUE,NOW(),'PARENT','0772200300',34);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.riad','Riad','Bencherif','riad.bencherif@gmail.com',FALSE,TRUE,NOW(),'PARENT','0772300400',35);
INSERT INTO users_users (password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,role,phone,address_id) VALUES ('pbkdf2_sha256$1200000$R6snFdPgbeGREQ96rtgt3O$ZY9NB4peT3QP6byO3kAORj2J2kk3/+5DMrNal2vhTjA=',NULL,FALSE,'parent.nadia2','Nadia','Boumediene','nadia.boumediene@gmail.com',FALSE,TRUE,NOW(),'PARENT','0772400500',36);

-- ============================================================
-- STEP 4: SECRETAIRE PROFILES — SKIPPED
-- users_secretaire table does not exist in Django models.
-- Secretaries are stored as ADMIN users in users_users.

-- ============================================================
-- STEP 5: DOCTOR PROFILES
-- ============================================================
INSERT INTO users_doctors (user_id,specialty_id,bio,horaire_travail,actif,ville,photo,numero_ordre_medecins)
SELECT u.id,s.id,'Spécialiste en pneumologie pédiatrique, 12 ans expérience. Expert asthme infantile et pathologies respiratoires chroniques.','Dim-Jeu 08h-16h',TRUE,'Oran','','31-MED-0041'
FROM users_users u, users_specialty s WHERE u.username='dr.amrani' AND s.name='Pneumologie pédiatrique';

INSERT INTO users_doctors (user_id,specialty_id,bio,horaire_travail,actif,ville,photo,numero_ordre_medecins)
SELECT u.id,s.id,'Pédiatre généraliste spécialisée dans le suivi des maladies chroniques de l enfant. Diabète, maladies auto-immunes.','Dim-Jeu 09h-17h',TRUE,'Oran','','31-MED-0087'
FROM users_users u, users_specialty s WHERE u.username='dr.khelif' AND s.name='Pédiatrie générale';

INSERT INTO users_doctors (user_id,specialty_id,bio,horaire_travail,actif,ville,photo,numero_ordre_medecins)
SELECT u.id,s.id,'Ophtalmologiste pédiatrique. Expert en strabisme, myopie précoce et pathologies oculaires.','Lun-Jeu 08h30-15h30',TRUE,'Oran','','31-MED-0152'
FROM users_users u, users_specialty s WHERE u.username='dr.benali' AND s.name='Ophtalmologie pédiatrique';

INSERT INTO users_doctors (user_id,specialty_id,bio,horaire_travail,actif,ville,photo,numero_ordre_medecins)
SELECT u.id,s.id,'Pneumologue pédiatrique spécialisée dans les infections respiratoires récidivantes et la mucoviscidose.','Dim-Mer 08h-14h',TRUE,'Bir El Djir','','31-MED-0203'
FROM users_users u, users_specialty s WHERE u.username='dr.meziani' AND s.name='Pneumologie pédiatrique';

INSERT INTO users_doctors (user_id,specialty_id,bio,horaire_travail,actif,ville,photo,numero_ordre_medecins)
SELECT u.id,s.id,'Pédiatre généraliste avec expertise en maladies rares et pathologies métaboliques de l enfant.','Dim-Jeu 10h-18h',TRUE,'Oran','','31-MED-0244'
FROM users_users u, users_specialty s WHERE u.username='dr.boudiaf' AND s.name='Pédiatrie générale';

-- ============================================================
-- STEP 6: PATIENTS (50 enfants)
-- ============================================================
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Rayan','Boudiaf','2018-03-15','M','A+','0661111111','','2024-01-10' FROM users_users u WHERE u.username='parent.lina';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Sara','Boudiaf','2020-07-22','F','A+','0661111111','','2024-01-10' FROM users_users u WHERE u.username='parent.lina';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Amine','Mansouri','2016-11-08','M','O+','0662222222','','2023-09-05' FROM users_users u WHERE u.username='parent.ahmed';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Nour','Mansouri','2019-02-14','F','B+','0662222222','','2023-09-05' FROM users_users u WHERE u.username='parent.ahmed';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Imane','Ouali','2017-06-30','F','AB+','0663333333','','2023-11-20' FROM users_users u WHERE u.username='parent.yousra';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Yasser','Djaafri','2015-04-18','M','B-','0664444444','','2022-06-01' FROM users_users u WHERE u.username='parent.karim';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Lyna','Djaafri','2018-09-03','F','O-','0664444444','','2022-06-01' FROM users_users u WHERE u.username='parent.karim';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Hamza','Belarbi','2014-12-25','M','A-','0665555555','','2022-03-14' FROM users_users u WHERE u.username='parent.nadia';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Ilyasse','Rahmani','2016-08-11','M','O+','0666666666','','2023-02-28' FROM users_users u WHERE u.username='parent.sofiane';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Rima','Rahmani','2019-05-06','F','AB-','0666666666','','2023-02-28' FROM users_users u WHERE u.username='parent.sofiane';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Adam','Bensalem','2017-01-19','M','B+','0667777777','','2023-07-07' FROM users_users u WHERE u.username='parent.meriem';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Wissam','Bensalem','2020-10-30','M','A+','0667777777','','2023-07-07' FROM users_users u WHERE u.username='parent.meriem';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Safa','Tlemcani','2015-03-22','F','O+','0668888888','','2022-11-11' FROM users_users u WHERE u.username='parent.hassan';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Rayane','Saidi','2013-07-14','M','A-','0669999999','','2022-01-05' FROM users_users u WHERE u.username='parent.houria';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Chaima','Saidi','2016-02-28','F','B+','0669999999','','2022-01-05' FROM users_users u WHERE u.username='parent.houria';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Karim','Bengana','2017-05-10','M','O+','0770111222','','2023-04-20' FROM users_users u WHERE u.username='parent.farid';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Manel','Ferroukhi','2019-09-01','F','A+','0770222333','','2023-06-15' FROM users_users u WHERE u.username='parent.zineb';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Anes','Ferroukhi','2021-02-14','M','A+','0770222333','','2023-06-15' FROM users_users u WHERE u.username='parent.zineb';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Ryad','Kaci','2016-12-03','M','B+','0770333444','','2022-08-30' FROM users_users u WHERE u.username='parent.mourad';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Lina','Cherif','2020-04-18','F','O-','0770444555','','2024-02-05' FROM users_users u WHERE u.username='parent.amina';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Walid','Boussaid','2014-08-22','M','AB+','0770555666','','2023-10-10' FROM users_users u WHERE u.username='parent.rachid';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Assia','Hadj','2018-11-05','F','A-','0770666777','','2023-03-22' FROM users_users u WHERE u.username='parent.hayat';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Oussama','Bouziane','2015-06-17','M','O+','0770777888','','2022-12-01' FROM users_users u WHERE u.username='parent.bilal';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Inasse','Bouziane','2018-03-09','F','O+','0770777888','','2022-12-01' FROM users_users u WHERE u.username='parent.bilal';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Djawad','Mekki','2021-07-28','M','B-','0770888999','','2024-03-01' FROM users_users u WHERE u.username='parent.sabrina';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Selma','Ziani','2016-01-11','F','AB+','0770999000','','2023-08-18' FROM users_users u WHERE u.username='parent.omar';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Ilyes','Ghali','2013-10-24','M','A+','0771100200','','2022-05-09' FROM users_users u WHERE u.username='parent.naima';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Rania','Ghali','2017-04-30','F','B+','0771100200','','2022-05-09' FROM users_users u WHERE u.username='parent.naima';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Zakaria','Medjdoub','2019-08-15','M','O+','0771200300','','2023-11-14' FROM users_users u WHERE u.username='parent.tarek';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Yasmine','Benyahia','2018-02-20','F','A+','0771300400','','2023-05-20' FROM users_users u WHERE u.username='parent.sihem';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Anis','Haddar','2015-09-12','M','O-','0771400500','','2022-09-03' FROM users_users u WHERE u.username='parent.lotfi';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Ritaj','Haddar','2020-12-05','F','O-','0771400500','','2022-09-03' FROM users_users u WHERE u.username='parent.lotfi';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Hana','Bensmain','2017-07-07','F','B+','0771500600','','2024-01-08' FROM users_users u WHERE u.username='parent.malika';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Mohamed','Dif','2016-03-25','M','A-','0771600700','','2023-07-25' FROM users_users u WHERE u.username='parent.yacine';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Ghizlane','Baali','2019-11-18','F','AB-','0771700800','','2022-10-12' FROM users_users u WHERE u.username='parent.wafa';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Youssef','Baali','2022-01-03','M','AB-','0771700800','','2022-10-12' FROM users_users u WHERE u.username='parent.wafa';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Nour El Houda','Tebbal','2018-06-14','F','O+','0771800900','','2023-02-14' FROM users_users u WHERE u.username='parent.abdelkader';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Romaissa','Sellal','2017-10-08','F','A+','0772000100','','2022-07-30' FROM users_users u WHERE u.username='parent.hanane';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Adem','Sellal','2020-05-22','M','A+','0772000100','','2022-07-30' FROM users_users u WHERE u.username='parent.hanane';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Bilel','Boudinar','2015-08-31','M','B+','0772100200','','2023-09-11' FROM users_users u WHERE u.username='parent.hocine';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Amira','Bouhelal','2016-04-19','F','O+','0772200300','','2022-04-06' FROM users_users u WHERE u.username='parent.khadija';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Fares','Bouhelal','2019-09-27','M','O+','0772200300','','2022-04-06' FROM users_users u WHERE u.username='parent.khadija';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Ilham','Bencherif','2018-12-10','F','A-','0772300400','','2023-12-01' FROM users_users u WHERE u.username='parent.riad';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Taim','Boumediene','2014-05-05','M','AB+','0772400500','','2022-03-17' FROM users_users u WHERE u.username='parent.nadia2';
INSERT INTO users_patients (parent_id,first_name,last_name,birth_date,gender,groupe_sanguin,telephone_parent,email,date_creation_dossier) SELECT u.id,'Israe','Boumediene','2017-08-21','F','AB+','0772400500','','2022-03-17' FROM users_users u WHERE u.username='parent.nadia2';

-- ============================================================
-- STEP 7: ALLERGIES (20)
-- ============================================================
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Pollens de graminées','MODEREE','Rhinite et larmoiements intenses au printemps. Éternuements fréquents.','2023-03-10' FROM users_patients p WHERE p.first_name='Imane' AND p.last_name='Ouali';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Acariens','LEGERE','Légère toux nocturne et congestion nasale en hiver.','2023-11-05' FROM users_patients p WHERE p.first_name='Rayan' AND p.last_name='Boudiaf';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Pénicilline','SEVERE','Réaction anaphylactique documentée. NE PAS PRESCRIRE.','2022-06-20' FROM users_patients p WHERE p.first_name='Amine' AND p.last_name='Mansouri';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Arachides','CRITIQUE','Allergie sévère. Adrénaline auto-injectable prescrite. Port permanent.','2021-08-15' FROM users_patients p WHERE p.first_name='Hamza' AND p.last_name='Belarbi';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Lait de vache','MODEREE','Intolérance protéines lait. Régime sans lactose strict.','2020-03-22' FROM users_patients p WHERE p.first_name='Wissam' AND p.last_name='Bensalem';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Latex','LEGERE','Réaction cutanée au contact du latex. Éviter gants latex.','2023-01-14' FROM users_patients p WHERE p.first_name='Yasser' AND p.last_name='Djaafri';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Ibuprofène','MODEREE','Urticaire après prise ibuprofène. Privilégier paracétamol.','2022-09-08' FROM users_patients p WHERE p.first_name='Safa' AND p.last_name='Tlemcani';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Poils de chat','LEGERE','Éternuements et yeux rouges au contact des félins.','2024-02-20' FROM users_patients p WHERE p.first_name='Nour' AND p.last_name='Mansouri';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Oeufs','MODEREE','Urticaire et vomissements après ingestion. Éviction stricte.','2023-05-15' FROM users_patients p WHERE p.first_name='Manel' AND p.last_name='Ferroukhi';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Gluten','MODEREE','Diarrhées chroniques et ballonnements. Régime sans gluten suivi.','2022-11-30' FROM users_patients p WHERE p.first_name='Yasmine' AND p.last_name='Benyahia';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Amoxicilline','SEVERE','Angioedème suite à amoxicilline. Alternative céphalosporine.','2023-08-07' FROM users_patients p WHERE p.first_name='Ghizlane' AND p.last_name='Baali';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Aspirine','MODEREE','Crise d asthme déclenchée. Contre-indication absolue.','2021-12-18' FROM users_patients p WHERE p.first_name='Ilyasse' AND p.last_name='Rahmani';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Poussière de maison','LEGERE','Rhinite allergique persistante. Purificateur d air recommandé.','2022-04-02' FROM users_patients p WHERE p.first_name='Karim' AND p.last_name='Bengana';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Noix','CRITIQUE','Anaphylaxie sévère. Auto-injecteur adrénaline. Port permanent.','2023-09-21' FROM users_patients p WHERE p.first_name='Romaissa' AND p.last_name='Sellal';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Sulfamides','MODEREE','Rash cutané généralisé après sulfaméthoxazole.','2022-07-14' FROM users_patients p WHERE p.first_name='Oussama' AND p.last_name='Bouziane';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Moisissures','LEGERE','Rhinite et toux sèche en période humide.','2023-10-05' FROM users_patients p WHERE p.first_name='Lyna' AND p.last_name='Djaafri';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Fraises','LEGERE','Urticaire localisée aux lèvres. Éviction conseillée.','2024-01-20' FROM users_patients p WHERE p.first_name='Hana' AND p.last_name='Bensmain';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Codéine','MODEREE','Nausées intenses et vomissements. Éviter opioïdes faibles.','2023-06-11' FROM users_patients p WHERE p.first_name='Walid' AND p.last_name='Boussaid';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Pollen de cyprès','MODEREE','Rhinite saisonnière sévère. Antihistaminique préventif.','2022-03-25' FROM users_patients p WHERE p.first_name='Selma' AND p.last_name='Ziani';
INSERT INTO medical_allergie (patient_id,nom,reaction,description,date_detection) SELECT p.id,'Lait de soja','LEGERE','Réaction croisée avec lait vache. Régime adapté.','2021-09-08' FROM users_patients p WHERE p.first_name='Ritaj' AND p.last_name='Haddar';

-- ============================================================
-- STEP 8: ANTECEDENTS (29)
-- FIX: type_antecedent 'NEUROLOGIQUE' and 'GENETIQUE' are now
-- valid because we added them to the Antecedent model
-- ============================================================
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Bronchite aiguë traitée par amoxicilline. Guérison complète.','MEDICAL','2023-02-14' FROM users_patients p WHERE p.first_name='Rayan' AND p.last_name='Boudiaf';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Diabète de type 1 diagnostiqué septembre 2022. Insulinothérapie en cours.','MEDICAL','2022-09-01' FROM users_patients p WHERE p.first_name='Amine' AND p.last_name='Mansouri';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Amygdalectomie suite à angines récidivantes. Guérison complète.','CHIRURGICAL','2024-01-15' FROM users_patients p WHERE p.first_name='Imane' AND p.last_name='Ouali';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Antécédents familiaux d asthme (père et grand-père paternel).','FAMILIAL','2023-05-20' FROM users_patients p WHERE p.first_name='Sara' AND p.last_name='Boudiaf';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Otite moyenne aiguë récidivante. 4 épisodes 2021-2023. Pose de drains.','MEDICAL','2021-04-10' FROM users_patients p WHERE p.first_name='Hamza' AND p.last_name='Belarbi';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Fracture radius droit suite à chute. Plâtre 6 semaines.','CHIRURGICAL','2022-07-03' FROM users_patients p WHERE p.first_name='Yasser' AND p.last_name='Djaafri';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Asthme modéré diagnostiqué 2021. Traitement fond budésonide.','MEDICAL','2021-10-18' FROM users_patients p WHERE p.first_name='Ilyasse' AND p.last_name='Rahmani';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Grand-père paternel diabétique T2. Mère asthmatique.','FAMILIAL','2023-03-01' FROM users_patients p WHERE p.first_name='Rayane' AND p.last_name='Saidi';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Strabisme convergent corrigé chirurgicalement. Port de lunettes.','CHIRURGICAL','2022-04-25' FROM users_patients p WHERE p.first_name='Safa' AND p.last_name='Tlemcani';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Myopie évolutive depuis 4 ans. Suivi ophtalmologique annuel.','MEDICAL','2021-09-12' FROM users_patients p WHERE p.first_name='Chaima' AND p.last_name='Saidi';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Convulsions fébriles à 18 mois. Bilan neurologique normal.','MEDICAL','2019-01-30' FROM users_patients p WHERE p.first_name='Wissam' AND p.last_name='Bensalem';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Eczéma atopique depuis la naissance. Traitement émollients et dermocorticoïdes.','MEDICAL','2020-08-14' FROM users_patients p WHERE p.first_name='Lyna' AND p.last_name='Djaafri';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Antécédents familiaux mucoviscidose (oncle maternel).','FAMILIAL','2023-06-10' FROM users_patients p WHERE p.first_name='Rima' AND p.last_name='Rahmani';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Adénoïdectomie mars 2023. Amélioration respiration nasale.','CHIRURGICAL','2023-03-18' FROM users_patients p WHERE p.first_name='Adam' AND p.last_name='Bensalem';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Prématurité à 34 SA. Séjour néonatal 3 semaines.','MEDICAL','2018-09-10' FROM users_patients p WHERE p.first_name='Karim' AND p.last_name='Bengana';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Cardiopathie congénitale CIV fermée spontanément à 2 ans.','MEDICAL','2021-07-22' FROM users_patients p WHERE p.first_name='Ryad' AND p.last_name='Kaci';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Epilepsie partielle bénigne de l enfance. Traitement valproate.','MEDICAL','2022-03-14' FROM users_patients p WHERE p.first_name='Ilyes' AND p.last_name='Ghali';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Luxation congénitale de hanche. Traitement orthopédique à la naissance.','CHIRURGICAL','2020-02-10' FROM users_patients p WHERE p.first_name='Yasmine' AND p.last_name='Benyahia';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Trisomie 21. Suivi multidisciplinaire régulier.','AUTRE','2016-04-05' FROM users_patients p WHERE p.first_name='Anis' AND p.last_name='Haddar';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Reflux gastro-oesophagien sévère néonatal. Fundoplicature.','CHIRURGICAL','2022-03-01' FROM users_patients p WHERE p.first_name='Youssef' AND p.last_name='Baali';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Retard de langage. Suivi orthophoniste depuis 3 ans.','MEDICAL','2021-11-08' FROM users_patients p WHERE p.first_name='Taim' AND p.last_name='Boumediene';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Maladie coeliaque confirmée par biopsie. Régime sans gluten strict.','MEDICAL','2023-01-25' FROM users_patients p WHERE p.first_name='Adem' AND p.last_name='Sellal';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Scoliose idiopathique débutante. Kinésithérapie en cours.','MEDICAL','2023-07-19' FROM users_patients p WHERE p.first_name='Walid' AND p.last_name='Boussaid';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Bronchiolite sévère à VRS à 3 mois. Hospitalisation 10 jours.','MEDICAL','2021-12-20' FROM users_patients p WHERE p.first_name='Djawad' AND p.last_name='Mekki';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Père diabétique T1. Risque familial élevé. Surveillance glycémique annuelle.','FAMILIAL','2022-08-15' FROM users_patients p WHERE p.first_name='Zakaria' AND p.last_name='Medjdoub';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Dermite atopique modérée depuis 18 mois. Traitement émollients.','MEDICAL','2023-02-07' FROM users_patients p WHERE p.first_name='Hana' AND p.last_name='Bensmain';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Hernie inguinale droite opérée à 2 ans. Aucune complication.','CHIRURGICAL','2021-05-14' FROM users_patients p WHERE p.first_name='Mohamed' AND p.last_name='Dif';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Asthme sévère avec 2 hospitalisations en 2022.','MEDICAL','2022-05-30' FROM users_patients p WHERE p.first_name='Bilel' AND p.last_name='Boudinar';
INSERT INTO medical_antecedent (patient_id,description,type_antecedent,date_declaration) SELECT p.id,'Hypothyroïdie congénitale. Levothyroxine depuis la naissance. TSH normalisée.','MEDICAL','2019-01-12' FROM users_patients p WHERE p.first_name='Ilham' AND p.last_name='Bencherif';

-- ============================================================
-- STEP 9: APPOINTMENTS (19 total)
-- FIX: created_by now references sec.fatima / sec.karima (valid users)
-- ============================================================

-- COMPLETED (8)
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-03-10 09:00:00','09:00:00','Toux persistante','Toux seche 3 semaines, légère fièvre le soir.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.amrani' JOIN users_patients p ON p.first_name='Rayan' AND p.last_name='Boudiaf' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-03-15 10:30:00','10:30:00','Contrôle diabète','Contrôle trimestriel glycémie.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.khelif' JOIN users_patients p ON p.first_name='Amine' AND p.last_name='Mansouri' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-03-20 08:30:00','08:30:00','Allergie saisonnière','Rhinite allergique, larmoiements, éternuements.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.amrani' JOIN users_patients p ON p.first_name='Imane' AND p.last_name='Ouali' JOIN users_users u ON u.username='sec.karima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-03-25 11:00:00','11:00:00','Contrôle asthme','Suivi asthme modéré, évaluation traitement fond.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.amrani' JOIN users_patients p ON p.first_name='Ilyasse' AND p.last_name='Rahmani' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-04-01 09:30:00','09:30:00','Bilan ophtalmologique','Contrôle annuel vue. Myopie évolutive.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.benali' JOIN users_patients p ON p.first_name='Chaima' AND p.last_name='Saidi' JOIN users_users u ON u.username='sec.karima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-04-05 14:00:00','14:00:00','Otite aiguë','Douleur oreille droite 2 jours, fièvre 38.5C.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.meziani' JOIN users_patients p ON p.first_name='Hamza' AND p.last_name='Belarbi' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-04-25 14:00:00','14:00:00','Suivi maladie coeliaque','Contrôle sérologie et régime sans gluten.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.khelif' JOIN users_patients p ON p.first_name='Yasmine' AND p.last_name='Benyahia' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-04-28 09:00:00','09:00:00','Fièvre prolongée','Fièvre 39C persistante 6 jours sans cause.','COMPLETED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.boudiaf' JOIN users_patients p ON p.first_name='Mohamed' AND p.last_name='Dif' JOIN users_users u ON u.username='sec.karima';

-- CONFIRMED (3)
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-06 10:30:00','10:30:00','Contrôle diabète','Contrôle mensuel glycémie et ajustement insuline.','CONFIRMED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.khelif' JOIN users_patients p ON p.first_name='Amine' AND p.last_name='Mansouri' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-08 09:00:00','09:00:00','Suivi asthme','Réévaluation traitement budésonide.','CONFIRMED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.amrani' JOIN users_patients p ON p.first_name='Ilyasse' AND p.last_name='Rahmani' JOIN users_users u ON u.username='sec.karima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-10 11:00:00','11:00:00','Bilan vue','Contrôle lunettes, adaptation correction.','CONFIRMED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.benali' JOIN users_patients p ON p.first_name='Safa' AND p.last_name='Tlemcani' JOIN users_users u ON u.username='sec.fatima';

-- PENDING (4)
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-15 09:00:00','09:00:00','Toux persistante','Toux grasse 10 jours malgré sirop.','PENDING',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.amrani' JOIN users_patients p ON p.first_name='Rayan' AND p.last_name='Boudiaf' JOIN users_users u ON u.username='sec.karima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-16 10:00:00','10:00:00','Rhinite','Renouvellement traitement rhinite allergique.','PENDING',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.meziani' JOIN users_patients p ON p.first_name='Nour' AND p.last_name='Mansouri' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-18 15:00:00','15:00:00','Contrôle strabisme','Suivi post-op strabisme 1 an après.','PENDING',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.benali' JOIN users_patients p ON p.first_name='Safa' AND p.last_name='Tlemcani' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-22 11:00:00','11:00:00','Toux seche nocturne','Toux nocturne depuis 2 semaines. Possible asthme.','PENDING',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.amrani' JOIN users_patients p ON p.first_name='Bilel' AND p.last_name='Boudinar' JOIN users_users u ON u.username='sec.karima';

-- CANCELLED (3)
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-04-22 14:00:00','14:00:00','Bilan ophtalmologique','Contrôle annuel vue.','CANCELLED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.benali' JOIN users_patients p ON p.first_name='Nour' AND p.last_name='Mansouri' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-04-28 11:00:00','11:00:00','Douleur genou','Douleur genou droit suite à chute.','CANCELLED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.khelif' JOIN users_patients p ON p.first_name='Yasser' AND p.last_name='Djaafri' JOIN users_users u ON u.username='sec.fatima';
INSERT INTO consultations_appointment (doctor_id,patient_id,created_by_id,date_rdv,heure,motif,reason,status,created_at,updated_at) SELECT d.id,p.id,u.id,'2026-05-02 09:00:00','09:00:00','Contrôle diabète','Bilan mensuel.','CANCELLED',NOW(),NOW() FROM users_doctors d JOIN users_users du ON d.user_id=du.id AND du.username='dr.khelif' JOIN users_patients p ON p.first_name='Amine' AND p.last_name='Mansouri' JOIN users_users u ON u.username='sec.karima';

-- ============================================================
-- STEP 10: CONSULTATIONS (8 — une par COMPLETED appointment)
-- ============================================================
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-03-10 09:30:00',22.0,110.0,37.8,'Quelques râles bronchiques bilatéraux. Gorge légèrement rouge. Pas de détresse respiratoire. Enfant actif et coopératif.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Rayan' AND p.last_name='Boudiaf' AND a.status='COMPLETED' AND a.date_rdv::date='2026-03-10';
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-03-15 11:00:00',38.5,128.0,36.9,'Glycémie à jeun 1.85 g/L. HbA1c 7.2%. Bon équilibre glycémique global. Pas de complications. Croissance normale.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Amine' AND p.last_name='Mansouri' AND a.status='COMPLETED' AND a.date_rdv::date='2026-03-15';
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-03-20 09:00:00',22.5,112.0,37.2,'Rhinite allergique confirmée. Légère congestion nasale bilatérale. Yeux légèrement rouges. Pas de fièvre.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Imane' AND p.last_name='Ouali' AND a.status='COMPLETED' AND a.date_rdv::date='2026-03-20';
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-03-25 11:30:00',35.0,132.0,37.0,'Asthme modéré bien contrôlé. Peak-flow 85% normale. Pas de crise depuis 2 mois. Technique inhalation correcte.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Ilyasse' AND p.last_name='Rahmani' AND a.status='COMPLETED' AND a.date_rdv::date='2026-03-25';
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-04-01 10:00:00',32.0,130.0,36.8,'Myopie stabilisée à -2.50 dioptries. Fond d oeil normal. Prochaine consultation dans 6 mois.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Chaima' AND p.last_name='Saidi' AND a.status='COMPLETED' AND a.date_rdv::date='2026-04-01';
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-04-05 14:30:00',29.0,122.0,38.5,'Otite moyenne aiguë droite confirmée. Tympan rouge et bombé. Enfant algique. Antibiothérapie débutée.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Hamza' AND p.last_name='Belarbi' AND a.status='COMPLETED' AND a.date_rdv::date='2026-04-05';
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-04-25 14:30:00',21.0,114.0,37.0,'Anticorps anti-transglutaminase négatifs. Bonne adhérence au régime sans gluten. Croissance reprend normalement.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Yasmine' AND p.last_name='Benyahia' AND a.status='COMPLETED' AND a.date_rdv::date='2026-04-25';
INSERT INTO consultations_consultation (appointment_id,date_consultation,poids,taille,temperature,observation) SELECT a.id,'2026-04-28 09:30:00',27.0,124.0,39.1,'Fièvre isolée 39.1C. TDR positif streptocoque A. Angine érythémateuse confirmée. Antibiothérapie prescrite.' FROM consultations_appointment a JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Mohamed' AND p.last_name='Dif' AND a.status='COMPLETED' AND a.date_rdv::date='2026-04-28';

-- ============================================================
-- STEP 11: DIAGNOSTICS (8)
-- ============================================================
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Bronchite aiguë','INFECTIEUX','MODEREE','Bronchite virale avec surinfection bactérienne possible. Antibiothérapie recommandée.','Votre enfant a une bronchite. Donnez les médicaments, gardez-le au chaud et faites-lui boire beaucoup. Revenez si fièvre > 39C.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Rayan' AND p.last_name='Boudiaf' AND a.date_rdv::date='2026-03-10';
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Diabète de type 1','CHRONIQUE','MODEREE','Diabète bien équilibré. HbA1c satisfaisante. Continuer protocole insulinique actuel.','Le diabète de votre enfant est bien contrôlé. Continuez les injections d insuline et surveillez la glycémie quotidiennement.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Amine' AND p.last_name='Mansouri' AND a.date_rdv::date='2026-03-15';
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Rhinite allergique saisonnière','ALLERGIQUE','LEGERE','Allergie aux pollens confirmée cliniquement. Antihistaminique et corticoïde nasal recommandés.','Votre enfant est allergique aux pollens. Gardez les fenêtres fermées au printemps et donnez le médicament chaque matin.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Imane' AND p.last_name='Ouali' AND a.date_rdv::date='2026-03-20';
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Asthme modéré persistant','ALLERGIQUE','MODEREE','Asthme bien contrôlé sous budésonide. Peak-flow satisfaisant. Maintenir traitement de fond.','L asthme est bien contrôlé. Ne jamais arrêter le traitement même quand votre enfant va bien. Ventoline en cas de crise.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Ilyasse' AND p.last_name='Rahmani' AND a.date_rdv::date='2026-03-25';
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Myopie évolutive','CHRONIQUE','LEGERE','Myopie stable 6 mois. Correction optique adaptée. Contrôle biannuel recommandé.','La vue est stable. Votre enfant doit porter ses lunettes en permanence, surtout à l école.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Chaima' AND p.last_name='Saidi' AND a.date_rdv::date='2026-04-01';
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Otite moyenne aiguë droite','INFECTIEUX','MODEREE','OMA droite avec bombement tympanique. Amoxicilline 50mg/kg/j 8 jours.','Votre enfant a une infection de l oreille. Donnez l antibiotique 3 fois par jour sans interruption. Revenez si pas d amélioration après 48h.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Hamza' AND p.last_name='Belarbi' AND a.date_rdv::date='2026-04-05';
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Maladie coeliaque équilibrée','DIGESTIF','LEGERE','Sérologie négative = bonne adhérence régime. Croissance en voie de normalisation.','Votre enfant suit bien le régime sans gluten. Continuez ainsi, sa croissance reprend normalement.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Yasmine' AND p.last_name='Benyahia' AND a.date_rdv::date='2026-04-25';
INSERT INTO consultations_diagnostic (consultation_id,nom_maladie,type_maladie,gravite,commentaire_medical,explication_parent) SELECT c.id,'Angine streptococcique','INFECTIEUX','MODEREE','TDR positif streptocoque A. Antibiothérapie amoxicilline 10 jours.','Votre enfant a une angine à microbe. Donnez l antibiotique 10 jours sans interrompre, même si amélioration.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id WHERE p.first_name='Mohamed' AND p.last_name='Dif' AND a.date_rdv::date='2026-04-28';

-- ============================================================
-- STEP 12: TRAITEMENTS (13)
-- ============================================================
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Amoxicilline 500mg','1 cp 3x/jour','7 jours','Prendre pendant les repas. Ne pas interrompre même si amélioration.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Rayan' AND p.last_name='Boudiaf' AND a.date_rdv::date='2026-03-10';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Salbutamol (Ventoline)','2 bouffées','À la demande','En cas de gêne respiratoire. Max 4 fois par jour.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Rayan' AND p.last_name='Boudiaf' AND a.date_rdv::date='2026-03-10';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Insuline Novorapid','Selon protocole glycémique','Continu','Injection avant chaque repas selon glycémie.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Amine' AND p.last_name='Mansouri' AND a.date_rdv::date='2026-03-15';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Insuline Lantus','Selon protocole','Continu','1 injection le soir avant coucher. Adapter dose selon glycémie matinale.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Amine' AND p.last_name='Mansouri' AND a.date_rdv::date='2026-03-15';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Loratadine 5mg','1 cp/matin','30 jours','Prendre avant le petit déjeuner. Éviter exposition aux pollens.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Imane' AND p.last_name='Ouali' AND a.date_rdv::date='2026-03-20';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Flixonase spray nasal','1 dose/narine','30 jours','Appliquer le matin après réveil. Bien moucher avant utilisation.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Imane' AND p.last_name='Ouali' AND a.date_rdv::date='2026-03-20';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Budésonide (Pulmicort) 200mcg','2 bouffées matin et soir','Continu','Traitement de fond. Ne jamais arrêter sans avis médical.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Ilyasse' AND p.last_name='Rahmani' AND a.date_rdv::date='2026-03-25';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Amoxicilline + Acide clavulanique 1g','3x/jour','8 jours','Si allergie pénicilline connue contacter immédiatement le médecin.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Hamza' AND p.last_name='Belarbi' AND a.date_rdv::date='2026-04-05';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Paracétamol 250mg','4x/jour si fièvre','5 jours','Donner si temperature > 38.5C. Espacer prises de 6h minimum.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Hamza' AND p.last_name='Belarbi' AND a.date_rdv::date='2026-04-05';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Amoxicilline 500mg','3x/jour','10 jours','Terminer la totalité du traitement. Revenir si pas amélioration après 48h.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Mohamed' AND p.last_name='Dif' AND a.date_rdv::date='2026-04-28';
INSERT INTO consultations_traitement (consultation_id,medicament,dose,duree,instructions) SELECT c.id,'Paracétamol 250mg sirop','3x/jour si fièvre','5 jours','Max 60mg/kg/jour. Donner avec eau. Ne pas dépasser la dose prescrite.' FROM consultations_consultation c JOIN consultations_appointment a ON c.appointment_id=a.id JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Mohamed' AND p.last_name='Dif' AND a.date_rdv::date='2026-04-28';

-- ============================================================
-- STEP 13: DOCUMENTS (3 — FIX: use documents_document table)
-- FIX: table is documents_document not medical_document
-- FIX: field is uploaded_by_id not id_utilisateur_id
-- FIX: field is type_doc not type
-- FIX: field is url_stockage (same) ✓
-- ============================================================
INSERT INTO documents_document (patient_id,consultation_id,nom_fichier,type_doc,fichier,url_stockage,date_upload)
SELECT p.id,c.id,'ordonnance_rayan_20260310.pdf','ORDONNANCE','documents/ordonnances/rayan_20260310.pdf','documents/ordonnances/rayan_20260310.pdf',NOW()
FROM users_patients p JOIN consultations_consultation c ON c.appointment_id IN (SELECT a.id FROM consultations_appointment a WHERE a.patient_id=p.id AND a.date_rdv::date='2026-03-10')
WHERE p.first_name='Rayan' AND p.last_name='Boudiaf';

INSERT INTO documents_document (patient_id,consultation_id,nom_fichier,type_doc,fichier,url_stockage,date_upload)
SELECT p.id,c.id,'bilan_hba1c_amine_20260315.pdf','ANALYSE','documents/analyses/amine_hba1c_20260315.pdf','documents/analyses/amine_hba1c_20260315.pdf',NOW()
FROM users_patients p JOIN consultations_consultation c ON c.appointment_id IN (SELECT a.id FROM consultations_appointment a WHERE a.patient_id=p.id AND a.date_rdv::date='2026-03-15')
WHERE p.first_name='Amine' AND p.last_name='Mansouri';

INSERT INTO documents_document (patient_id,consultation_id,nom_fichier,type_doc,fichier,url_stockage,date_upload)
SELECT p.id,c.id,'serologie_coeliaque_yasmine_20260425.pdf','ANALYSE','documents/analyses/yasmine_transglutaminase_20260425.pdf','documents/analyses/yasmine_transglutaminase_20260425.pdf',NOW()
FROM users_patients p JOIN consultations_consultation c ON c.appointment_id IN (SELECT a.id FROM consultations_appointment a WHERE a.patient_id=p.id AND a.date_rdv::date='2026-04-25')
WHERE p.first_name='Yasmine' AND p.last_name='Benyahia';

-- ============================================================
-- STEP 14: NOTIFICATIONS (7)
-- ============================================================
INSERT INTO notifications_notification (recipient_id,notif_type,title,message,is_read,created_at,appointment_id) SELECT u.id,'REMINDER','Nouveau rendez-vous','Nouveau RDV de Rayan Boudiaf le 15/05/2026 à 09:00.',FALSE,NOW(),a.id FROM users_users u, consultations_appointment a JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Rayan' AND a.status='PENDING' AND a.date_rdv::date='2026-05-15' WHERE u.username='dr.amrani';
INSERT INTO notifications_notification (recipient_id,notif_type,title,message,is_read,created_at,appointment_id) SELECT u.id,'REMINDER','Rendez-vous confirmé','Le RDV de Amine avec Dr. Khelif est confirmé pour le 06/05/2026.',FALSE,NOW(),a.id FROM users_users u, consultations_appointment a JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Amine' AND a.status='CONFIRMED' AND a.date_rdv::date='2026-05-06' WHERE u.username='parent.ahmed';
INSERT INTO notifications_notification (recipient_id,notif_type,title,message,is_read,created_at,appointment_id) SELECT u.id,'REMINDER','Nouveau rendez-vous','Nouveau RDV de Nour Mansouri le 16/05/2026 à 10:00.',FALSE,NOW(),a.id FROM users_users u, consultations_appointment a JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Nour' AND a.status='PENDING' AND a.date_rdv::date='2026-05-16' WHERE u.username='dr.meziani';
INSERT INTO notifications_notification (recipient_id,notif_type,title,message,is_read,created_at,appointment_id) SELECT u.id,'MESSAGE','Rendez-vous annulé','Le RDV de Nour prévu le 22/04/2026 a été annulé.',TRUE,NOW(),a.id FROM users_users u, consultations_appointment a JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Nour' AND a.status='CANCELLED' AND a.date_rdv::date='2026-04-22' WHERE u.username='parent.ahmed';
INSERT INTO notifications_notification (recipient_id,notif_type,title,message,is_read,created_at,appointment_id) SELECT u.id,'REMINDER','Rendez-vous confirmé','RDV de Ilyasse avec Dr. Amrani confirmé pour le 08/05/2026.',FALSE,NOW(),a.id FROM users_users u, consultations_appointment a JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Ilyasse' AND a.status='CONFIRMED' AND a.date_rdv::date='2026-05-08' WHERE u.username='parent.sofiane';
INSERT INTO notifications_notification (recipient_id,notif_type,title,message,is_read,created_at,appointment_id) SELECT u.id,'MESSAGE','Résultats disponibles','Les résultats de Yasmine Benyahia sont disponibles.',FALSE,NOW(),a.id FROM users_users u, consultations_appointment a JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Yasmine' AND a.status='COMPLETED' AND a.date_rdv::date='2026-04-25' WHERE u.username='parent.sihem';
INSERT INTO notifications_notification (recipient_id,notif_type,title,message,is_read,created_at,appointment_id) SELECT u.id,'MESSAGE','Compte rendu consultation','Le compte rendu de Mohamed Dif du 28/04 est disponible.',FALSE,NOW(),a.id FROM users_users u, consultations_appointment a JOIN users_patients p ON a.patient_id=p.id AND p.first_name='Mohamed' AND a.status='COMPLETED' AND a.date_rdv::date='2026-04-28' WHERE u.username='parent.yacine';

-- ============================================================
-- STEP 15: MESSAGES
-- FIX applied: table is messaging_message (Django app = messaging)
-- ============================================================
INSERT INTO notifications_message (expediteur_id,destinataire_id,contenu,date_envoi,lu)
SELECT e.id,d.id,'Bonjour docteur, Rayan tousse encore beaucoup depuis hier soir, dois-je m inquiéter ?',NOW()-INTERVAL '2 days',TRUE FROM users_users e,users_users d WHERE e.username='parent.lina' AND d.username='dr.amrani';

INSERT INTO notifications_message (expediteur_id,destinataire_id,contenu,date_envoi,lu)
SELECT e.id,d.id,'Bonjour. Si fièvre > 39C ou respiration difficile, venez aux urgences. Sinon continuez le traitement.',NOW()-INTERVAL '2 days'+INTERVAL '1 hour',TRUE FROM users_users e,users_users d WHERE e.username='dr.amrani' AND d.username='parent.lina';

INSERT INTO notifications_message (expediteur_id,destinataire_id,contenu,date_envoi,lu)
SELECT e.id,d.id,'Docteur, la glycémie de Amine était à 3.2 g/L ce matin après le petit déjeuner, est-ce normal ?',NOW()-INTERVAL '1 day',FALSE FROM users_users e,users_users d WHERE e.username='parent.ahmed' AND d.username='dr.khelif';

INSERT INTO notifications_message (expediteur_id,destinataire_id,contenu,date_envoi,lu)
SELECT e.id,d.id,'Bonjour, est-il possible de décaler le RDV du 17 mai pour Wissam ? Nous ne pouvons pas nous libérer.',NOW()-INTERVAL '12 hours',FALSE FROM users_users e,users_users d WHERE e.username='parent.meriem' AND d.username='sec.karima';

-- ============================================================
-- STEP 16: TRACEACTION
-- FIX: field names are user_id, action, table_concernee, id_enregistrement, timestamp
-- (not id_utilisateur_id, type_action, date_heure)
-- ============================================================
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','users_patients',NOW()-INTERVAL '15 days' FROM users_users u WHERE u.username='sec.fatima';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','users_patients',NOW()-INTERVAL '14 days' FROM users_users u WHERE u.username='sec.fatima';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','consultations_appointment',NOW()-INTERVAL '13 days' FROM users_users u WHERE u.username='sec.karima';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','consultations_consultation',NOW()-INTERVAL '12 days' FROM users_users u WHERE u.username='dr.amrani';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','consultations_diagnostic',NOW()-INTERVAL '11 days' FROM users_users u WHERE u.username='dr.amrani';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','consultations_traitement',NOW()-INTERVAL '10 days' FROM users_users u WHERE u.username='dr.amrani';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'UPDATE','users_patients',NOW()-INTERVAL '9 days' FROM users_users u WHERE u.username='sec.fatima';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','medical_allergie',NOW()-INTERVAL '8 days' FROM users_users u WHERE u.username='dr.khelif';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','medical_antecedent',NOW()-INTERVAL '7 days' FROM users_users u WHERE u.username='dr.khelif';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'UPDATE','consultations_appointment',NOW()-INTERVAL '6 days' FROM users_users u WHERE u.username='sec.karima';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'DELETE','consultations_appointment',NOW()-INTERVAL '5 days' FROM users_users u WHERE u.username='admin';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','medical_allergie',NOW()-INTERVAL '4 days' FROM users_users u WHERE u.username='dr.amrani';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','medical_antecedent',NOW()-INTERVAL '3 days' FROM users_users u WHERE u.username='dr.boudiaf';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'UPDATE','users_users',NOW()-INTERVAL '2 days' FROM users_users u WHERE u.username='admin';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'UPDATE','consultations_appointment',NOW()-INTERVAL '6 hours' FROM users_users u WHERE u.username='sec.fatima';
INSERT INTO users_traceaction (user_id,action,table_concernee,timestamp) SELECT u.id,'INSERT','notifications_notification',NOW()-INTERVAL '2 hours' FROM users_users u WHERE u.username='sec.karima';

-- ============================================================
-- AFTER IMPORT — run in Django shell:
-- python manage.py shell
-- from users.models import Users
-- from django.contrib.auth.hashers import make_password
-- Users.objects.all().update(password=make_password('hospital123'))
-- exit()
--
-- VERIFICATION:
-- SELECT 'users_specialty' AS t, COUNT(*) FROM users_specialty
-- UNION ALL SELECT 'users_users',               COUNT(*) FROM users_users
-- UNION ALL SELECT 'users_secretaire',          COUNT(*) FROM users_secretaire
-- UNION ALL SELECT 'users_doctors',             COUNT(*) FROM users_doctors
-- UNION ALL SELECT 'users_patients',            COUNT(*) FROM users_patients
-- UNION ALL SELECT 'consultations_appointment', COUNT(*) FROM consultations_appointment
-- UNION ALL SELECT 'consultations_consultation',COUNT(*) FROM consultations_consultation
-- UNION ALL SELECT 'consultations_diagnostic',  COUNT(*) FROM consultations_diagnostic
-- UNION ALL SELECT 'consultations_traitement',  COUNT(*) FROM consultations_traitement
-- UNION ALL SELECT 'medical_allergie',          COUNT(*) FROM medical_allergie
-- UNION ALL SELECT 'medical_antecedent',        COUNT(*) FROM medical_antecedent
-- UNION ALL SELECT 'documents_document',        COUNT(*) FROM documents_document
-- UNION ALL SELECT 'notifications_notification',COUNT(*) FROM notifications_notification
-- UNION ALL SELECT 'notifications_message',     COUNT(*) FROM notifications_message
-- UNION ALL SELECT 'users_traceaction',         COUNT(*) FROM users_traceaction;
-- Expected: 3·41·2·5·50·19·8·8·13·20·29·3·7·4·16
-- ============================================================
