# Generated by Django 6.0.5 on 2026-05-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_appointment_heure_appointment_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='type_maladie',
            field=models.CharField(choices=[('AIGU', 'Aigu'), ('CHRONIQUE', 'Chronique'), ('ALLERGIQUE', 'Allergique'), ('INFECTIEUX', 'Infectieux'), ('NEUROLOGIQUE', 'Neurologique'), ('CARDIOLOGIQUE', 'Cardiologique'), ('DIGESTIF', 'Digestif'), ('ENDOCRINIEN', 'Endocrinien'), ('GENETIQUE', 'Génétique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='duree',
            field=models.CharField(max_length=100),
        ),
    ]
