# Generated by Django 6.0.5 on 2026-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_alter_diagnostic_type_maladie_alter_traitement_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traitement',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='patient',
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='type_maladie',
            field=models.CharField(choices=[('AIGU', 'Aigu'), ('CHRONIQUE', 'Chronique'), ('ALLERGIQUE', 'Allergique'), ('INFECTIEUX', 'Infectieux'), ('NEUROLOGIQUE', 'Neurologique'), ('CARDIOLOGIQUE', 'Cardiologique'), ('DIGESTIF', 'Digestif'), ('ENDOCRINIEN', 'Endocrinien'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='duree',
            field=models.CharField(help_text='ex: 7 jours, 2 semaines', max_length=100),
        ),
        migrations.DeleteModel(
            name='LabResult',
        ),
    ]
