# Generated by Django 6.0.5 on 2026-05-23 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='url_stockage',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(choices=[('ORDONNANCE', 'Ordonnance'), ('RADIO', 'Radiographie'), ('ANALYSE', 'Analyse de laboratoire'), ('EXAMEN', 'Examen complémentaire'), ('COMPTE_RENDU', 'Compte rendu'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
