# Generated by Django 6.0.5 on 2026-05-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='notifications_message',
        ),
    ]
