# Generated by Django 6.0.5 on 2026-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_traitement_doctor_traitement_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='motif',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
