# Generated by Django 6.0.5 on 2026-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergie',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='type_antecedent',
            field=models.CharField(choices=[('MEDICAL', 'Médical'), ('CHIRURGICAL', 'Chirurgical'), ('FAMILIAL', 'Familial'), ('AUTRE', 'Autre'), ('NEUROLOGIQUE', 'Neurologique'), ('GENETIQUE', 'Génétique')], default='MEDICAL', max_length=20),
        ),
        migrations.AlterModelTable(
            name='allergie',
            table='medical_allergie',
        ),
        migrations.AlterModelTable(
            name='antecedent',
            table='medical_antecedent',
        ),
    ]
